apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
data:
  mongodb-username: {{ .Values.secret.mongodb_username }}
  mongodb-password: {{ .Values.secret.mongodb_password }}