apiVersion: v2
name: guestbook
appVersion: "2.0"
description: A Helm chart for Guestbook 2.0 
version: 1.2.2
type: application

dependencies:
  - name: backend
    version: ~1.2.2
    repository: http://localhost:8080
  - name: frontend
    version: ^1.2.0
    repository: http://localhost:8080
  - name: mongodb
    version: 7.8.x
    repository: https://charts.helm.sh/stable




